export const kanji = [
  {
    id: 1,
    level: "n5",
    image: "",
    kanji: "一",
    kunYomi: "hito(tsu)",
    onYomi: "ichi",
    hiragana: "いち",
    meaning: "တစ်ခု / တစ်",
    others: [
      { kanji: "一人", hiragana: "ひとり", meaning: "တစ်ယောက်တည်း" },
      { kanji: "一日", hiragana: "ついたち", meaning: "လဆန်း ၁ ရက်နေ့" },
      {
        kanji: "一番",
        hiragana: "いちばん",
        meaning: "နံပါတ်တစ် / အကောင်းဆုံး",
      },
      { kanji: "一分", hiragana: "いっぷん", meaning: "တစ်မိနစ်" },
    ],
  },
  {
    id: 2,
    level: "n5",
    image: "",
    kanji: "二",
    kunYomi: "futa(tsu)",
    onYomi: "ni",
    hiragana: "に",
    meaning: "နှစ်ခု / နှစ်",
    others: [
      { kanji: "二人", hiragana: "ふたり", meaning: "နှစ်ယောက်" },
      { kanji: "二日", hiragana: "ふつか", meaning: "၂ ရက်နေ့" },
      { kanji: "二月", hiragana: "にがつ", meaning: "ဖေဖော်ဝါရီလ" },
      { kanji: "二十歳", hiragana: "はたち", meaning: "အသက် ၂၀" },
    ],
  },
  {
    id: 3,
    level: "n5",
    kanji: "三",
    image: "",
    kunYomi: "mit(tsu)",
    onYomi: "san",
    hiragana: "さん",
    meaning: "သုံးခု / သုံး",
    others: [
      { kanji: "三日", hiragana: "みっか", meaning: "၃ ရက်နေ့" },
      { kanji: "三月", hiragana: "さんがつ", meaning: "မတ်လ" },
      { kanji: "三人", hiragana: "さんにん", meaning: "သုံးယောက်" },
      { kanji: "三日目", hiragana: "みっかめ", meaning: "တတိယမြောက်နေ့" },
    ],
  },
  {
    id: 4,
    level: "n5",
    kanji: "四",
    image: "",
    kunYomi: "yot(tsu)",
    onYomi: "shi",
    hiragana: "よん",
    meaning: "လေးခု / လေး",
    others: [
      { kanji: "四日", hiragana: "よっか", meaning: "၄ ရက်နေ့" },
      { kanji: "四月", hiragana: "しがつ", meaning: "ဧပြီလ" },
      { kanji: "四人", hiragana: "よにん", meaning: "လေးယောက်" },
      { kanji: "四季", hiragana: "しき", meaning: "ရာသီလေးခု" },
    ],
  },
  {
    id: 5,
    level: "n5",
    kanji: "五",
    image: "",
    kunYomi: "it(tsu)",
    onYomi: "go",
    hiragana: "ご",
    meaning: "ငါးခု / ငါး",
    others: [
      { kanji: "五日", hiragana: "いつか", meaning: "၅ ရက်နေ့" },
      { kanji: "五月", hiragana: "ごがつ", meaning: "မေလ" },
      { kanji: "五人", hiragana: "ごにん", meaning: "ငါးယောက်" },
      { kanji: "五分", hiragana: "ごふん", meaning: "ငါးမိနစ်" },
    ],
  },
  {
    id: 6,
    level: "n5",
    kanji: "六",
    image: "",
    kunYomi: "mut(tsu)",
    onYomi: "roku",
    hiragana: "ろく",
    meaning: "ခြောက်ခု / ခြောက်",
    others: [
      { kanji: "六日", hiragana: "むいか", meaning: "၆ ရက်နေ့" },
      { kanji: "六月", hiragana: "ろくがつ", meaning: "ဇွန်လ" },
      { kanji: "六分", hiragana: "ろっぷん", meaning: "ခြောက်မိနစ်" },
      { kanji: "六人", hiragana: "ろくにん", meaning: "ခြောက်ယောက်" },
    ],
  },
  {
    id: 7,
    level: "n5",
    kanji: "七",
    image: "",
    kunYomi: "nana(tsu)",
    onYomi: "shichi",
    hiragana: "なな",
    meaning: "ခုနစ်ခု / ခုနစ်",
    others: [
      { kanji: "七日", hiragana: "なのか", meaning: "၇ ရက်နေ့" },
      { kanji: "七月", hiragana: "しちがつ", meaning: "ဇူလိုင်လ" },
      { kanji: "七夕", hiragana: "たなばた", meaning: "တာနာဘာတာပွဲတော်" },
      { kanji: "七分", hiragana: "ななふん", meaning: "ခုနစ်မိနစ်" },
    ],
  },
  {
    id: 8,
    level: "n5",
    kanji: "八",
    image: "",
    kunYomi: "yat(tsu)",
    onYomi: "hachi",
    hiragana: "はち",
    meaning: "ရှစ်ခု / ရှစ်",
    others: [
      { kanji: "八日", hiragana: "ようか", meaning: "၈ ရက်နေ့" },
      { kanji: "八月", hiragana: "ဟာချီဂတ်ဆု", meaning: "ဩဂုတ်လ" },
      { kanji: "八百屋", hiragana: "やおや", meaning: "ဟင်းသီးဟင်းရွက်ဆိုင်" },
      { kanji: "八分", hiragana: "ဟာပွန်", meaning: "ရှစ်မိနစ်" },
    ],
  },
  {
    id: 9,
    level: "n5",
    kanji: "九",
    image: "",
    kunYomi: "kokono(tsu)",
    onYomi: "kyuu / ku",
    hiragana: "きゅう",
    meaning: "ကိုးခု / ကိုး",
    others: [
      { kanji: "九日", hiragana: "ここのか", meaning: "၉ ရက်နေ့" },
      { kanji: "九月", hiragana: "くがつ", meaning: "စက်တင်ဘာလ" },
      { kanji: "九時", hiragana: "くじ", meaning: "ကိုးနာရီ" },
      { kanji: "九人", hiragana: "きゅうにん", meaning: "ကိုးယောက်" },
    ],
  },
  {
    id: 10,
    level: "n5",
    kanji: "十",
    image: "",
    kunYomi: "too",
    onYomi: "juu",
    hiragana: "じゅう",
    meaning: "ဆယ်ခု / ဆယ်",
    others: [
      { kanji: "十日", hiragana: "とおか", meaning: "၁၀ ရက်နေ့" },
      { kanji: "十月", hiragana: "じゅうがつ", meaning: "အောက်တိုဘာလ" },
      { kanji: "十分", hiragana: "じゅうぶん", meaning: "လုံလောက်သော" },
      { kanji: "十人", hiragana: "じゅうにん", meaning: "ဆယ်ယောက်" },
    ],
  },
  {
    id: 11,
    level: "n5",
    kanji: "百",
    image: "",
    kunYomi: "N/A",
    onYomi: "hyaku",
    hiragana: "ひゃく",
    meaning: "တစ်ရာ",
    others: [
      { kanji: "三百", hiragana: "さんびゃく", meaning: "သုံးရာ" },
      { kanji: "六百", hiragana: "ろっぴゃく", meaning: "ခြောက်ရာ" },
      { kanji: "八百", hiragana: "はっぴゃく", meaning: "ရှစ်ရာ" },
      { kanji: "百貨店", hiragana: "ひゃっかてん", meaning: "ကုန်တိုက်" },
    ],
  },
  {
    id: 12,
    level: "n5",
    kanji: "千",
    image: "",
    kunYomi: "chi",
    onYomi: "sen",
    hiragana: "せん",
    meaning: "တစ်ထောင်",
    others: [
      { kanji: "三千", hiragana: "さんぜん", meaning: "သုံးထောင်" },
      { kanji: "八千", hiragana: "はっせん", meaning: "ရှစ်ထောင်" },
      { kanji: "千円", hiragana: "せんえん", meaning: "တစ်ထောင်ယန်း" },
      { kanji: "千葉県", hiragana: "ちばけん", meaning: "ချီဘခရိုင်" },
    ],
  },
  {
    id: 13,
    level: "n5",
    kanji: "万",
    image: "",
    kunYomi: "N/A",
    onYomi: "man / ban",
    hiragana: "まん",
    meaning: "တစ်သောင်း",
    others: [
      { kanji: "一万円", hiragana: "いちまんえん", meaning: "တစ်သောင်းယန်း" },
      { kanji: "万国", hiragana: "ばんこく", meaning: "နိုင်ငံအားလုံး" },
      {
        kanji: "万歳",
        hiragana: "ばんざい",
        meaning: "ဘန်ဇိုင်း (အောင်ပွဲခံအော်ဟစ်သံ)",
      },
      { kanji: "万年筆", hiragana: "まんねんひつ", meaning: "ဖောင်တိန်" },
    ],
  },
  {
    id: 14,
    level: "n5",
    kanji: "円",
    image: "",
    kunYomi: "maru(i)",
    onYomi: "en",
    hiragana: "えん",
    meaning: "ယန်းငွေ / ဝိုင်းသော",
    others: [
      { kanji: "五百円", hiragana: "ごひゃくえん", meaning: "ငါးရာယန်း" },
      { kanji: "円い", hiragana: "まるい", meaning: "ဝိုင်းသော" },
      {
        kanji: "円高",
        hiragana: "えんだか",
        meaning: "ယန်းငွေတန်ဖိုးတက်ခြင်း",
      },
      { kanji: "楕円", hiragana: "だえん", meaning: "ဘဲဥပုံ" },
    ],
  },
  {
    id: 15,
    level: "n5",
    kanji: "日",
    image: "",
    kunYomi: "hi / bi",
    onYomi: "nichi / jitsu",
    hiragana: "ひ",
    meaning: "နေ့ / နေ",
    others: [
      { kanji: "日曜日", hiragana: "にちようび", meaning: "တနင်္ဂနွေနေ့" },
      { kanji: "毎日", hiragana: "まいにち", meaning: "နေ့တိုင်း" },
      { kanji: "日本", hiragana: "にほん", meaning: "ဂျပန်" },
      { kanji: "祝日", hiragana: "しゅくじつ", meaning: "ရုံးပိတ်ရက်" },
    ],
  },
  {
    id: 16,
    level: "n5",
    kanji: "月",
    image: "",
    kunYomi: "tsuki",
    onYomi: "getsu / gatsu",
    hiragana: "つき",
    meaning: "လ / လမင်း",
    others: [
      { kanji: "月曜日", hiragana: "げつようび", meaning: "တနင်္လာနေ့" },
      { kanji: "一月", hiragana: "いちがつ", meaning: "ဇန်နဝါရီလ" },
      { kanji: "今月", hiragana: "こんげつ", meaning: "ဒီလ" },
      { kanji: "毎月", hiragana: "まいつき", meaning: "လတိုင်း" },
    ],
  },
  {
    id: 17,
    level: "n5",
    kanji: "火",
    image: "",
    kunYomi: "hi",
    onYomi: "ka",
    hiragana: "ひ",
    meaning: "မီး",
    others: [
      { kanji: "火曜日", hiragana: "かようび", meaning: "အင်္ဂါနေ့" },
      { kanji: "火山", hiragana: "かざん", meaning: "မီးတောင်" },
      { kanji: "火事", hiragana: "かじ", meaning: "မီးလောင်ခြင်း" },
      { kanji: "花火", hiragana: "はなび", meaning: "မီးရှူးမီးပန်း" },
    ],
  },
  {
    id: 18,
    level: "n5",
    kanji: "水",
    image: "",
    kunYomi: "mizu",
    onYomi: "sui",
    hiragana: "みず",
    meaning: "ရေ",
    others: [
      { kanji: "水曜日", hiragana: "すいようび", meaning: "ဗုဒ္ဓဟူးနေ့" },
      { kanji: "水道", hiragana: "すいどう", meaning: "ရေပိုက်ခေါင်း" },
      { kanji: "水泳", hiragana: "すいえい", meaning: "ရေကူးခြင်း" },
      { kanji: "水着", hiragana: "みずぎ", meaning: "ရေကူးဝတ်စုံ" },
    ],
  },
  {
    id: 19,
    level: "n5",
    kanji: "木",
    image: "",
    kunYomi: "ki",
    onYomi: "moku / boku",
    hiragana: "き",
    meaning: "သစ်ပင်",
    others: [
      { kanji: "木曜日", hiragana: "もくようび", meaning: "ကြာသပတေးနေ့" },
      { kanji: "大木", hiragana: "たいぼく", meaning: "သစ်ပင်ကြီး" },
      { kanji: "木星", hiragana: "もくせい", meaning: "ကြာသပတေးဂြိုဟ်" },
      {
        kanji: "木造",
        hiragana: "もくぞう",
        meaning: "သစ်သားဖြင့်ပြုလုပ်ထားသော",
      },
    ],
  },
  {
    id: 20,
    level: "n5",
    kanji: "金",
    image: "",
    kunYomi: "kane",
    onYomi: "kin",
    hiragana: "かね",
    meaning: "ရွှေ / ပိုက်ဆံ",
    others: [
      { kanji: "金曜日", hiragana: "きんようび", meaning: "သောကြာနေ့" },
      { kanji: "お金", hiragana: "おかね", meaning: "ပိုက်ဆံ" },
      { kanji: "金物", hiragana: "かなもの", meaning: "သံထည်ပစ္စည်း" },
      { kanji: "金魚", hiragana: "きんぎょ", meaning: "ရွှေငါး" },
    ],
  },
  {
    id: 21,
    level: "n5",
    kanji: "土",
    image: "",
    kunYomi: "tsuchi",
    onYomi: "do / to",
    hiragana: "つち",
    meaning: "မြေကြီး",
    others: [
      { kanji: "土曜日", hiragana: "どようび", meaning: "စနေနေ့" },
      { kanji: "土地", hiragana: "とち", meaning: "မြေနေရာ" },
      { kanji: "お土産", hiragana: "おみやげ", meaning: "လက်ဆောင်" },
      {
        kanji: "土木",
        hiragana: "どぼく",
        meaning: "မြို့ပြအင်ဂျင်နီယာလုပ်ငန်း",
      },
    ],
  },
  {
    id: 22,
    level: "n5",
    kanji: "人",
    image: "",
    kunYomi: "hito",
    onYomi: "jin / nin",
    hiragana: "ひと",
    meaning: "လူ",
    others: [
      { kanji: "日本人", hiragana: "にほんじん", meaning: "ဂျပန်လူမျိုး" },
      { kanji: "外国人", hiragana: "がいこくじん", meaning: "နိုင်ငံခြားသား" },
      { kanji: "大人", hiragana: "おとな", meaning: "လူကြီး" },
      { kanji: "恋人", hiragana: "こいびと", meaning: "ချစ်သူ" },
    ],
  },
  {
    id: 23,
    level: "n5",
    image: "",
    kanji: "年",
    kunYomi: "toshi",
    onYomi: "nen",
    hiragana: "とし",
    meaning: "နှစ် (Year)",
    others: [
      {
        kanji: "二〇二六年",
        hiragana: "にせんにじゅうろくねん",
        meaning: "၂၀၂၆ ခုနှစ်",
      },
      { kanji: "来年", hiragana: "らいねん", meaning: "နောက်နှစ်" },
      { kanji: "去年", hiragana: "きょねん", meaning: "မနှစ်က" },
      { kanji: "毎年", hiragana: "まいねん", meaning: "နှစ်တိုင်း" },
    ],
  },
  {
    id: 24,
    level: "n5",
    image: "",
    kanji: "今",
    kunYomi: "ima",
    onYomi: "kon / kin",
    hiragana: "いま",
    meaning: "ယခု",
    others: [
      { kanji: "今日", hiragana: "きょう", meaning: "ယနေ့" },
      { kanji: "今月", hiragana: "こんげつ", meaning: "ဒီလ" },
      { kanji: "今年", hiragana: "ことし", meaning: "ဒီနှစ်" },
      { kanji: "今週", hiragana: "こんしゅう", meaning: "ဒီအပတ်" },
    ],
  },
  {
    id: 25,
    level: "n5",
    kanji: "何",
    image: "",
    kunYomi: "nani / nan",
    onYomi: "ka",
    hiragana: "なに",
    meaning: "ဘာလဲ",
    others: [
      { kanji: "何時", hiragana: "なんじ", meaning: "ဘယ်နှစ်နာရီလဲ" },
      { kanji: "何人", hiragana: "なんにん", meaning: "ဘယ်နှစ်ယောက်လဲ" },
      { kanji: "何曜日", hiragana: "なんようび", meaning: "ဘယ်နေ့လဲ" },
      { kanji: "何か", hiragana: "なにか", meaning: "တစ်ခုခု" },
    ],
  },
  {
    id: 26,
    level: "n5",
    kanji: "上",
    kunYomi: "ue / a(garu)",
    onYomi: "jou",
    hiragana: "うえ",
    meaning: "အပေါ်",
    image: "https://api.example.com/images/kanji/ue.png",
    others: [
      {
        kanji: "上手",
        hiragana: "じょうず",
        meaning: "တော်သော / ကျွမ်းကျင်သော",
      },
      { kanji: "屋上", hiragana: "おくじょう", meaning: "တိုက်ခေါင်မိုး" },
      { kanji: "上がる", hiragana: "あがる", meaning: "တက်သည်" },
      { kanji: "上着", hiragana: "うわぎ", meaning: "အပေါ်အင်္ကျီ" },
    ],
  },
  {
    id: 27,
    level: "n5",
    kanji: "下",
    kunYomi: "shita / sa(garu)",
    onYomi: "ka / ge",
    hiragana: "した",
    meaning: "အောက်",
    image: "https://api.example.com/images/kanji/shita.png",
    others: [
      { kanji: "下手", hiragana: "へた", meaning: "ညံ့သော" },
      { kanji: "地下鉄", hiragana: "ちかてつ", meaning: "မြေအောက်ရထား" },
      { kanji: "下がる", hiragana: "さがる", meaning: "ဆင်းသည် / ကျသည်" },
      { kanji: "下着", hiragana: "したぎ", meaning: "အတွင်းခံ" },
    ],
  },
  {
    id: 28,
    level: "n5",
    kanji: "左",
    kunYomi: "hidari",
    onYomi: "sa",
    hiragana: "ひだり",
    meaning: "ဘယ်ဘက်",
    image: "https://api.example.com/images/kanji/hidari.png",
    others: [
      { kanji: "左側", hiragana: "ひだりがわ", meaning: "ဘယ်ဘက်ခြမ်း" },
      { kanji: "左手", hiragana: "ひだりて", meaning: "ဘယ်လက်" },
      { kanji: "左右", hiragana: "さゆう", meaning: "ဘယ်ညာ" },
      { kanji: "左利き", hiragana: "ひだりきき", meaning: "ဘယ်သန်" },
    ],
  },
  {
    id: 29,
    level: "n5",
    kanji: "右",
    kunYomi: "migi",
    onYomi: "u / yuu",
    hiragana: "みぎ",
    meaning: "ညာဘက်",
    image: "https://api.example.com/images/kanji/migi.png",
    others: [
      { kanji: "右側", hiragana: "みぎがわ", meaning: "ညာဘက်ခြမ်း" },
      { kanji: "右手", hiragana: "みぎて", meaning: "ညာလက်" },
      { kanji: "右折", hiragana: "うせつ", meaning: "ညာကွေ့ခြင်း" },
      { kanji: "右足", hiragana: "みぎあし", meaning: "ညာခြေထောက်" },
    ],
  },
  {
    id: 30,
    level: "n5",
    kanji: "中",
    kunYomi: "naka",
    onYomi: "chuu",
    hiragana: "なか",
    meaning: "အလယ် / အထဲ",
    image: "https://api.example.com/images/kanji/naka.png",
    others: [
      { kanji: "中国", hiragana: "ちゅうごく", meaning: "တရုတ်နိုင်ငံ" },
      { kanji: "一日中", hiragana: "いちにちじゅう", meaning: "တစ်နေကုန်" },
      {
        kanji: "中学校",
        hiragana: "ちゅうがっこう",
        meaning: "အလယ်တန်းကျောင်း",
      },
      { kanji: "中心", hiragana: "ちゅうしん", meaning: "ဗဟိုချက်" },
    ],
  },
  {
    id: 31,
    level: "n5",
    kanji: "大",
    kunYomi: "oo(kii)",
    onYomi: "dai / tai",
    hiragana: "おおきい",
    meaning: "ကြီးသော",
    image: "https://api.example.com/images/kanji/ookii.png",
    others: [
      { kanji: "大学", hiragana: "だいがく", meaning: "တက္ကသိုလ်" },
      { kanji: "大使館", hiragana: "たいしかん", meaning: "သံရုံး" },
      {
        kanji: "大丈夫",
        hiragana: "だいじょうぶ",
        meaning: "ကိစ္စမရှိပါ / အဆင်ပြေပါတယ်",
      },
      {
        kanji: "大会",
        hiragana: "たいかい",
        meaning: "ပြိုင်ပွဲကြီး / ညီလာခံ",
      },
    ],
  },
  {
    id: 32,
    level: "n5",
    kanji: "小",
    kunYomi: "chii(sai) / ko",
    onYomi: "shou",
    hiragana: "ちいさい",
    meaning: "သေးသော",
    image: "https://api.example.com/images/kanji/chiisai.png",
    others: [
      {
        kanji: "小学校",
        hiragana: "しょうがっこう",
        meaning: "မူလတန်းကျောင်း",
      },
      { kanji: "小説", hiragana: "しょうせつ", meaning: "ဝတ္ထု" },
      { kanji: "小包", hiragana: "こづつみ", meaning: "ချောထုပ်" },
      { kanji: "小川", hiragana: "おがわ", meaning: "ချောင်းငယ်" },
    ],
  },
  {
    id: 33,
    level: "n5",
    kanji: "長",
    kunYomi: "naga(i)",
    onYomi: "chou",
    hiragana: "ながい",
    meaning: "ရှည်သော / ခေါင်းဆောင်",
    image: "https://api.example.com/images/kanji/nagai.png",
    others: [
      {
        kanji: "社長",
        hiragana: "しゃちょう",
        meaning: "ကုမ္ပဏီပိုင်ရှင် / ဒါရိုက်တာ",
      },
      { kanji: "校長", hiragana: "こうちょう", meaning: "ကျောင်းအုပ်ကြီး" },
      { kanji: "身長", hiragana: "しんちょう", meaning: "အရပ်အမောင်း" },
      { kanji: "長男", hiragana: "ちょうなん", meaning: "သားကြီး" },
    ],
  },
  {
    id: 34,
    level: "n5",
    kanji: "多",
    kunYomi: "oo(i)",
    onYomi: "ta",
    hiragana: "おおい",
    meaning: "များသော",
    image: "https://api.example.com/images/kanji/ooi.png",
    others: [
      {
        kanji: "多分",
        hiragana: "たぶん",
        meaning: "ဖြစ်နိုင်ချေရှိသော / ဖြစ်နိုင်သည်",
      },
      { kanji: "多少", hiragana: "たしょう", meaning: "အနည်းငယ်" },
      { kanji: "多忙", hiragana: "たぼう", meaning: "အလွန်အလုပ်ရှုပ်သော" },
      { kanji: "多数", hiragana: "たすう", meaning: "အများစု" },
    ],
  },
  {
    id: 35,
    level: "n5",
    kanji: "少",
    kunYomi: "suku(nai) / suko(shi)",
    onYomi: "shou",
    hiragana: "すくない",
    meaning: "နည်းသော",
    image: "https://api.example.com/images/kanji/sukunai.png",
    others: [
      { kanji: "少し", hiragana: "すこし", meaning: "နည်းနည်း" },
      { kanji: "少年", hiragana: "しょうねん", meaning: "ယောက်ျားလေး" },
      { kanji: "少女", hiragana: "しょうじょ", meaning: "မိန်းကလေး" },
      {
        kanji: "少々",
        hiragana: "しょうしょう",
        meaning: "ခဏလောက် / နည်းနည်းလောက်",
      },
    ],
  },
  {
    id: 36,
    level: "n5",
    kanji: "父",
    kunYomi: "chichi",
    onYomi: "fu",
    hiragana: "ちち",
    meaning: "အဖေ (ကိုယ့်အဖေ)",
    image: "https://api.example.com/images/kanji/chichi.png",
    others: [
      {
        kanji: "お父さん",
        hiragana: "おとうさん",
        meaning: "အဖေ (သူတစ်ပါးအဖေ သို့မဟုတ် ခေါ်သည့်အခါ)",
      },
      { kanji: "父親", hiragana: "ちちおや", meaning: "ဖခင်" },
      { kanji: "祖父", hiragana: "そふ", meaning: "အဘိုး" },
      { kanji: "父母", hiragana: "ふぼ", meaning: "မိဘ" },
    ],
  },
  {
    id: 37,
    level: "n5",
    kanji: "母",
    kunYomi: "haha",
    onYomi: "bo",
    hiragana: "はは",
    meaning: "အမေ (ကိုယ့်အမေ)",
    image: "https://api.example.com/images/kanji/haha.png",
    others: [
      {
        kanji: "お母さん",
        hiragana: "おかあさん",
        meaning: "အမေ (သူတစ်ပါးအမေ သို့မဟုတ် ခေါ်သည့်အခါ)",
      },
      { kanji: "母親", hiragana: "ははおや", meaning: "မိခင်" },
      { kanji: "祖母", hiragana: "そぼ", meaning: "အဘွား" },
      { kanji: "母語", hiragana: "ぼご", meaning: "မိခင်ဘာသာစကား" },
    ],
  },
  {
    id: 38,
    level: "n5",
    kanji: "友",
    kunYomi: "tomo",
    onYomi: "yuu",
    hiragana: "とも",
    meaning: "သူငယ်ချင်း",
    image: "https://api.example.com/images/kanji/tomo.png",
    others: [
      { kanji: "友達", hiragana: "ともだち", meaning: "သူငယ်ချင်းများ" },
      { kanji: "友人", hiragana: "ゆうじん", meaning: "မိတ်ဆွေ" },
      { kanji: "親友", hiragana: "しんゆう", meaning: "ရင်းနှီးသောသူငယ်ချင်း" },
      {
        kanji: "友情",
        hiragana: "ゆうじょう",
        meaning: "သံယောဇဉ် / ချစ်ကြည်ရေး",
      },
    ],
  },
  {
    id: 39,
    level: "n5",
    kanji: "男",
    kunYomi: "otoko",
    onYomi: "dan / nan",
    hiragana: "おとこ",
    meaning: "ယောက်ျား",
    image: "https://api.example.com/images/kanji/otoko.png",
    others: [
      { kanji: "男の子", hiragana: "おとこのこ", meaning: "ယောက်ျားလေး" },
      { kanji: "男性", hiragana: "だんせい", meaning: "အမျိုးသား" },
      { kanji: "長男", hiragana: "ちょうなん", meaning: "သားအကြီးဆုံး" },
      { kanji: "男子", hiragana: "だんし", meaning: "လူငယ်အမျိုးသား" },
    ],
  },
  {
    id: 40,
    level: "n5",
    kanji: "女",
    kunYomi: "onna",
    onYomi: "jo",
    hiragana: "おんな",
    meaning: "မိန်းမ",
    image: "https://api.example.com/images/kanji/onna.png",
    others: [
      { kanji: "女の子", hiragana: "おんなのこ", meaning: "မိန်းကလေး" },
      { kanji: "女性", hiragana: "じょせい", meaning: "အမျိုးသမီး" },
      { kanji: "長女", hiragana: "ちょうじょ", meaning: "သမီးအကြီးဆုံး" },
      { kanji: "女子", hiragana: "じょし", meaning: "လူငယ်အမျိုးသမီး" },
    ],
  },
  {
    id: 41,
    level: "n5",
    kanji: "行",
    kunYomi: "i(ku) / o行う",
    onYomi: "kou / gyou",
    hiragana: "いく",
    meaning: "သွားသည်",
    image: "https://api.example.com/images/kanji/iku.png",
    others: [
      { kanji: "銀行", hiragana: "ぎんこう", meaning: "ဘဏ်" },
      { kanji: "旅行", hiragana: "りょこう", meaning: "ခရီးသွားခြင်း" },
      {
        kanji: "行う",
        hiragana: "おこなう",
        meaning: "ပြုလုပ်သည် / ကျင်းပသည်",
      },
      { kanji: "二行目", hiragana: "にぎょうめ", meaning: "ဒုတိယစာကြောင်း" },
    ],
  },
  {
    id: 42,
    level: "n5",
    kanji: "来",
    kunYomi: "ku(ru) / ki(masu)",
    onYomi: "rai",
    hiragana: "くる",
    meaning: "လာသည်",
    image: "https://api.example.com/images/kanji/kuru.png",
    others: [
      { kanji: "来年", hiragana: "らいねん", meaning: "နောက်နှစ်" },
      { kanji: "来月", hiragana: "らいげつ", meaning: "နောက်လ" },
      { kanji: "来週", hiragana: "らいしゅう", meaning: "နောက်အပတ်" },
      { kanji: "未来", hiragana: "みらい", meaning: "အနာဂတ်" },
    ],
  },
  {
    id: 43,
    level: "n5",
    kanji: "食",
    kunYomi: "ta(beru)",
    onYomi: "shoku",
    hiragana: "たべる",
    meaning: "စားသည်",
    image: "https://api.example.com/images/kanji/taberu.png",
    others: [
      { kanji: "食べ物", hiragana: "たべもの", meaning: "အစားအစာ" },
      { kanji: "食堂", hiragana: "しょくどう", meaning: "ထမင်းစားဆောင်" },
      { kanji: "朝食", hiragana: "ちょうしょく", meaning: "မနက်စာ" },
      { kanji: "和食", hiragana: "わしょく", meaning: "ဂျပန်စာ" },
    ],
  },
  {
    id: 44,
    level: "n5",
    kanji: "飲",
    kunYomi: "no(mu)",
    onYomi: "in",
    hiragana: "のむ",
    meaning: "သောက်သည်",
    image: "https://api.example.com/images/kanji/nomu.png",
    others: [
      { kanji: "飲み物", hiragana: "のみもの", meaning: "သောက်စရာ" },
      { kanji: "飲食店", hiragana: "いんしょくてん", meaning: "စားသောက်ဆိုင်" },
      { kanji: "飲み会", hiragana: "のみかい", meaning: "သောက်စားပွဲ" },
      {
        kanji: "飲酒運転",
        hiragana: "いんしゅうんてん",
        meaning: "မူးယစ်မောင်းနှင်ခြင်း",
      },
    ],
  },
  {
    id: 45,
    level: "n5",
    kanji: "見",
    kunYomi: "mi(ru)",
    onYomi: "ken",
    hiragana: "みる",
    meaning: "ကြည့်သည် / မြင်သည်",
    image: "https://api.example.com/images/kanji/miru.png",
    others: [
      { kanji: "見学", hiragana: "けんがく", meaning: "လေ့လာရေးသွားခြင်း" },
      { kanji: "花見", hiragana: "はなみ", meaning: "ပန်းကြည့်ပွဲ" },
      { kanji: "意見", hiragana: "いけん", meaning: "သဘောထား / အမြင်" },
      { kanji: "見本", hiragana: "みほん", meaning: "နမူနာ" },
    ],
  },
  {
    id: 46,
    level: "n5",
    kanji: "聞",
    kunYomi: "ki(ku)",
    onYomi: "bun / mon",
    hiragana: "きく",
    meaning: "နားထောင်သည် / ကြားသည်",
    image: "https://api.example.com/images/kanji/kiku.png",
    others: [
      { kanji: "新聞", hiragana: "しんぶん", meaning: "သတင်းစာ" },
      {
        kanji: "聞き取り",
        hiragana: "ききとり",
        meaning: "နားထောင်မှုစွမ်းရည်",
      },
      {
        kanji: "前代未聞",
        hiragana: "ぜんだいみもん",
        meaning: "တစ်ခါမှမကြားဖူးသော",
      },
      { kanji: "聞こえる", hiragana: "きこえる", meaning: "ကြားရသည်" },
    ],
  },
  {
    id: 47,
    level: "n5",
    kanji: "読",
    kunYomi: "yo(mu)",
    onYomi: "doku",
    hiragana: "よむ",
    meaning: "ဖတ်သည်",
    image: "https://api.example.com/images/kanji/yomu.png",
    others: [
      { kanji: "読書", hiragana: "どくしょ", meaning: "စာဖတ်ခြင်း" },
      { kanji: "読み方", hiragana: "よみかた", meaning: "ဖတ်နည်း" },
      { kanji: "読者", hiragana: "どくしゃ", meaning: "စာဖတ်သူ" },
      { kanji: "難読", hiragana: "なんどく", meaning: "ဖတ်ရန်ခက်ခဲသော" },
    ],
  },
  {
    id: 48,
    level: "n5",
    kanji: "書",
    kunYomi: "ka(ku)",
    onYomi: "sho",
    hiragana: "かく",
    meaning: "ရေးသည်",
    image: "https://api.example.com/images/kanji/kaku.png",
    others: [
      { kanji: "辞書", hiragana: "じしょ", meaning: "အဘိဓာန်" },
      { kanji: "図書館", hiragana: "としょかん", meaning: "စာကြည့်တိုက်" },
      { kanji: "書き方", hiragana: "かきかた", meaning: "ရေးနည်း" },
      {
        kanji: "教科書",
        hiragana: "きょうかしょ",
        meaning: "သင်ရိုးညွှန်းတမ်းစာအုပ်",
      },
    ],
  },
  {
    id: 49,
    level: "n5",
    kanji: "話",
    kunYomi: "hana(su)",
    onYomi: "wa",
    hiragana: "はなす",
    meaning: "ပြောသည် / စကားပြောသည်",
    image: "https://api.example.com/images/kanji/hanasu.png",
    others: [
      { kanji: "電話", hiragana: "でんわ", meaning: "ဖုန်း" },
      { kanji: "会話", hiragana: "かいわ", meaning: "စကားပြောဆိုခြင်း" },
      { kanji: "お話し", hiragana: "おはなし", meaning: "ပုံပြင် / စကားပြော" },
      { kanji: "世話", hiragana: "せわ", meaning: "ပြုစုစောင့်ရှောက်ခြင်း" },
    ],
  },
  {
    id: 50,
    level: "n5",
    kanji: "買",
    kunYomi: "ka(u)",
    onYomi: "bai",
    hiragana: "かう",
    meaning: "ဝယ်သည်",
    image: "https://api.example.com/images/kanji/kau.png",
    others: [
      { kanji: "買い物", hiragana: "かいもの", meaning: "ဈေးဝယ်ခြင်း" },
      {
        kanji: "買収",
        hiragana: "ばいしゅう",
        meaning: "ဝယ်ယူခြင်း (business)",
      },
      { kanji: "売買", hiragana: "ばいばい", meaning: "အရောင်းအဝယ်" },
      { kanji: "買い手", hiragana: "かいて", meaning: "ဝယ်သူ" },
    ],
  },
  {
    id: 51,
    level: "n5",
    kanji: "学",
    kunYomi: "mana(bu)",
    onYomi: "gaku",
    hiragana: "まなぶ",
    meaning: "သင်ယူသည် / ပညာ",
    image: "https://api.example.com/images/kanji/gaku.png",
    others: [
      { kanji: "学生", hiragana: "がくせい", meaning: "ကျောင်းသား" },
      { kanji: "大学", hiragana: "だいがく", meaning: "တက္ကသိုလ်" },
      { kanji: "学校", hiragana: "がっこう", meaning: "ကျောင်း" },
      {
        kanji: "留学",
        hiragana: "りゅうがく",
        meaning: "နိုင်ငံခြားပညာတော်သင်",
      },
    ],
  },
  {
    id: 52,
    level: "n5",
    kanji: "校",
    kunYomi: "N/A",
    onYomi: "kou",
    hiragana: "こう",
    meaning: "ကျောင်း (အဆောက်အဦး)",
    image: "https://api.example.com/images/kanji/kou.png",
    others: [
      {
        kanji: "小学校",
        hiragana: "しょうがっこう",
        meaning: "မူလတန်းကျောင်း",
      },
      {
        kanji: "中学校",
        hiragana: "ちゅうがっこう",
        meaning: "အလယ်တန်းကျောင်း",
      },
      { kanji: "高校", hiragana: "こうこう", meaning: "အထက်တန်းကျောင်း" },
      { kanji: "校長", hiragana: "こうちょう", meaning: "ကျောင်းအုပ်ကြီး" },
    ],
  },
  {
    id: 53,
    level: "n5",
    kanji: "先",
    kunYomi: "saki",
    onYomi: "sen",
    hiragana: "さき",
    meaning: "အရင် / အလျင်",
    image: "https://api.example.com/images/kanji/sen.png",
    others: [
      { kanji: "先生", hiragana: "せんせい", meaning: "ဆရာ / ဆရာမ" },
      { kanji: "先週", hiragana: "せんしゅう", meaning: "ပြီးခဲ့သည့်အပတ်" },
      { kanji: "先月", hiragana: "せんげつ", meaning: "ပြီးခဲ့သည့်လ" },
      { kanji: "先に", hiragana: "さきに", meaning: "အရင်ဦးစွာ" },
    ],
  },
  {
    id: 54,
    level: "n5",
    kanji: "生",
    kunYomi: "i(kiru) / u(mareru) / nama",
    onYomi: "sei / shou",
    hiragana: "いきる",
    meaning: "အသက်ရှင်သည် / မွေးဖွားသည် / အစိမ်း",
    image: "https://api.example.com/images/kanji/sei.png",
    others: [
      { kanji: "誕生日", hiragana: "たんじょうび", meaning: "မွေးနေ့" },
      { kanji: "一生", hiragana: "いっしょう", meaning: "တစ်သက်တာ" },
      {
        kanji: "生年月日",
        hiragana: "せいねんがっぴ",
        meaning: "မွေးသက္ကရာဇ်",
      },
      { kanji: "生地", hiragana: "きじ", meaning: "အထည်စ / မုန့်အနှစ်" },
    ],
  },
  {
    id: 55,
    level: "n5",
    kanji: "山",
    kunYomi: "yama",
    onYomi: "san",
    hiragana: "やま",
    meaning: "တောင်",
    image: "https://api.example.com/images/kanji/yama.png",
    others: [
      { kanji: "火山", hiragana: "かざん", meaning: "မီးတောင်" },
      { kanji: "登山", hiragana: "とざん", meaning: "တောင်တက်ခြင်း" },
      { kanji: "山道", hiragana: "やまみち", meaning: "တောင်တက်လမ်း" },
      { kanji: "富士山", hiragana: "ふじさん", meaning: "ဖူဂျီတောင်" },
    ],
  },
  {
    id: 56,
    level: "n5",
    kanji: "川",
    kunYomi: "kawa",
    onYomi: "sen",
    hiragana: "かわ",
    meaning: "မြစ် / ချောင်း",
    image: "https://api.example.com/images/kanji/kawa.png",
    others: [
      { kanji: "小川", hiragana: "おがわ", meaning: "ချောင်းငယ်" },
      { kanji: "ナイル川", hiragana: "ないるがわ", meaning: "နိုင်းမြစ်" },
      { kanji: "川岸", hiragana: "かわぎし", meaning: "မြစ်ကမ်းနဖူး" },
      { kanji: "河川", hiragana: "かせん", meaning: "မြစ်ချောင်းများ" },
    ],
  },
  {
    id: 57,
    level: "n5",
    kanji: "田",
    kunYomi: "ta",
    onYomi: "den",
    hiragana: "た",
    meaning: "လယ်ကွင်း",
    image: "https://api.example.com/images/kanji/ta.png",
    others: [
      {
        kanji: "田中さん",
        hiragana: "たなかさん",
        meaning: "တာနာကာဆန် (နာမည်)",
      },
      { kanji: "水田", hiragana: "すいでん", meaning: "ရေသွင်းလယ်မြေ" },
      { kanji: "田舎", hiragana: "いなか", meaning: "တောရွာ" },
      { kanji: "田んぼ", hiragana: "たんぼ", meaning: "လယ်ကွင်း" },
    ],
  },
  {
    id: 58,
    level: "n5",
    kanji: "天",
    kunYomi: "ama",
    onYomi: "ten",
    hiragana: "あま",
    meaning: "ကောင်းကင်",
    image: "https://api.example.com/images/kanji/ten.png",
    others: [
      { kanji: "天気", hiragana: "てんき", meaning: "ရာသီဥတု" },
      {
        kanji: "天国",
        hiragana: "てんごく",
        meaning: "နိဗ္ဗာန် / ကောင်းကင်ဘုံ",
      },
      { kanji: "天皇", hiragana: "てんのう", meaning: "ဂျပန်ဧကရာဇ်" },
      { kanji: "天才", hiragana: "てんさい", meaning: "ပါရမီရှင်" },
    ],
  },
  {
    id: 59,
    level: "n5",
    kanji: "気",
    kunYomi: "N/A",
    onYomi: "ki / ke",
    hiragana: "き",
    meaning: "စိတ် / စွမ်းအင်",
    image: "https://api.example.com/images/kanji/ki.png",
    others: [
      { kanji: "元気", hiragana: "げんき", meaning: "နေကောင်းသည်" },
      { kanji: "気持ち", hiragana: "きもち", meaning: "ခံစားချက်" },
      { kanji: "人気", hiragana: "にんき", meaning: "လူကြိုက်များသော" },
      { kanji: "空気", hiragana: "くうき", meaning: "လေထု" },
    ],
  },
  {
    id: 60,
    level: "n5",
    kanji: "雨",
    kunYomi: "ame",
    onYomi: "u",
    hiragana: "あめ",
    meaning: "မိုး",
    image: "https://api.example.com/images/kanji/ame.png",
    others: [
      {
        kanji: "大雨",
        hiragana: "おおあめ",
        meaning: "မိုးသည်းထန်စွာရွာခြင်း",
      },
      { kanji: "雨天", hiragana: "うてん", meaning: "မိုးရွာသောရာသီဥတု" },
      { kanji: "雨水", hiragana: "あまみず", meaning: "မိုးရေ" },
      { kanji: "梅雨", hiragana: "つゆ", meaning: "မိုးရာသီ" },
    ],
  },
  {
    id: 61,
    level: "n5",
    kanji: "車",
    kunYomi: "kuruma",
    onYomi: "sha",
    hiragana: "くるま",
    meaning: "ကား / ဘီး",
    image: "https://api.example.com/images/kanji/kuruma.png",
    others: [
      { kanji: "電車", hiragana: "でんしゃ", meaning: "လျှပ်စစ်ရထား" },
      { kanji: "自転車", hiragana: "じてんしゃ", meaning: "စက်ဘီး" },
      { kanji: "救急車", hiragana: "きゅうきゅうしゃ", meaning: "လူနာတင်ကား" },
      { kanji: "駐車場", hiragana: "ちゅうしゃじょう", meaning: "ကားပါကင်" },
    ],
  },
  {
    id: 62,
    level: "n5",
    kanji: "門",
    kunYomi: "kado",
    onYomi: "mon",
    hiragana: "かど",
    meaning: "တံခါးပေါက်",
    image: "https://api.example.com/images/kanji/mon.png",
    others: [
      { kanji: "校門", hiragana: "こうもん", meaning: "ကျောင်းတံခါး" },
      { kanji: "専門", hiragana: "せんもん", meaning: "အထူးပြုဘာသာရပ်" },
      { kanji: "正門", hiragana: "せいもん", meaning: "ပင်မတံခါး" },
      {
        kanji: "門限",
        hiragana: "もんげん",
        meaning: "အိမ်ပြန်ချိန်ကန့်သတ်ချက်",
      },
    ],
  },
  {
    id: 63,
    level: "n5",
    kanji: "午",
    kunYomi: "N/A",
    onYomi: "go",
    hiragana: "ご",
    meaning: "မွန်းတည့်",
    image: "https://api.example.com/images/kanji/go_time.png",
    others: [
      { kanji: "午前", hiragana: "ごぜん", meaning: "နံနက်ပိုင်း (AM)" },
      { kanji: "午後", hiragana: "ごご", meaning: "မွန်းလွဲပိုင်း (PM)" },
      { kanji: "正午", hiragana: "しょうご", meaning: "မွန်းတည့် ၁၂ နာရီ" },
      {
        kanji: "午前中",
        hiragana: "ごぜんちゅう",
        meaning: "နံနက်ပိုင်းတစ်လျှောက်",
      },
    ],
  },
  {
    id: 64,
    level: "n5",
    kanji: "前",
    kunYomi: "mae",
    onYomi: "zen",
    hiragana: "まえ",
    meaning: "ရှေ့ / အရင်",
    image: "https://api.example.com/images/kanji/mae.png",
    others: [
      { kanji: "名前", hiragana: "なまえ", meaning: "နာမည်" },
      { kanji: "三日前", hiragana: "みっかまえ", meaning: "လွန်ခဲ့သော ၃ ရက်" },
      { kanji: "駅前", hiragana: "えきまえ", meaning: "ဘူတာရုံရှေ့" },
      {
        kanji: "前払い",
        hiragana: "まえばらい",
        meaning: "ကြိုတင်ငွေပေးချေခြင်း",
      },
    ],
  },
  {
    id: 65,
    level: "n5",
    kanji: "後",
    kunYomi: "ato / ushiro / nochi",
    onYomi: "go / kou",
    hiragana: "あと",
    meaning: "နောက် / ပြီးနောက်",
    image: "https://api.example.com/images/kanji/ato.png",
    others: [
      { kanji: "後ろ", hiragana: "うしろ", meaning: "အနောက်ဘက် (Position)" },
      { kanji: "後で", hiragana: "あとで", meaning: "ခဏနေရင် / ပြီးမှ" },
      { kanji: "最後", hiragana: "さいご", meaning: "နောက်ဆုံး" },
      { kanji: "後半", hiragana: "こうはん", meaning: "ဒုတိယပိုင်း" },
    ],
  },
  {
    id: 66,
    level: "n5",
    kanji: "東",
    kunYomi: "higashi",
    onYomi: "tou",
    hiragana: "ひがし",
    meaning: "အရှေ့ဘက်",
    image: "https://api.example.com/images/kanji/higashi.png",
    others: [
      { kanji: "東京", hiragana: "とうきょう", meaning: "တိုကျို" },
      {
        kanji: "東南アジア",
        hiragana: "とうなんあじあ",
        meaning: "အရှေ့တောင်အာရှ",
      },
      { kanji: "中東", hiragana: "ちゅうとう", meaning: "အရှေ့အလယ်ပိုင်း" },
      { kanji: "東口", hiragana: "ひがしぐち", meaning: "အရှေ့ဘက်အပေါက်" },
    ],
  },
  {
    id: 67,
    level: "n5",
    kanji: "西",
    kunYomi: "nishi",
    onYomi: "sei / sai",
    hiragana: "にし",
    meaning: "အနောက်ဘက်",
    image: "https://api.example.com/images/kanji/nishi.png",
    others: [
      { kanji: "北西", hiragana: "ほくせい", meaning: "အနောက်မြောက်" },
      { kanji: "関西", hiragana: "かんさい", meaning: "ခန်းဆိုင်းဒေသ" },
      { kanji: "西口", hiragana: "にしぐち", meaning: "အနောက်ဘက်အပေါက်" },
      {
        kanji: "西洋",
        hiragana: "せいよう",
        meaning: "အနောက်တိုင်းနိုင်ငံများ",
      },
    ],
  },
  {
    id: 68,
    level: "n5",
    kanji: "南",
    kunYomi: "minami",
    onYomi: "nan",
    hiragana: "みなみ",
    meaning: "တောင်ဘက်",
    image: "https://api.example.com/images/kanji/minami.png",
    others: [
      { kanji: "東南", hiragana: "とうなん", meaning: "အရှေ့တောင်" },
      { kanji: "南極", hiragana: "なんきょく", meaning: "တောင်ဝင်ရိုးစွန်း" },
      { kanji: "南米", hiragana: "なんべい", meaning: "တောင်အမေရိက" },
      { kanji: "南口", hiragana: "みなみぐち", meaning: "တောင်ဘက်အပေါက်" },
    ],
  },
  {
    id: 69,
    level: "n5",
    kanji: "北",
    kunYomi: "kita",
    onYomi: "hoku",
    hiragana: "きた",
    meaning: "မြောက်ဘက်",
    image: "https://api.example.com/images/kanji/kita.png",
    others: [
      { kanji: "北海道", hiragana: "ほっかいどう", meaning: "ဟော့ကိုင်းဒိုး" },
      { kanji: "北極", hiragana: "ほっきょく", meaning: "မြောက်ဝင်ရိုးစွန်း" },
      { kanji: "東北", hiragana: "とうほく", meaning: "တိုဟိုကုဒေသ" },
      { kanji: "北口", hiragana: "きたぐち", meaning: "မြောက်ဘက်အပေါက်" },
    ],
  },
  {
    id: 70,
    level: "n5",
    kanji: "名",
    kunYomi: "na",
    onYomi: "mei / myou",
    hiragana: "な",
    meaning: "နာမည်",
    image: "https://api.example.com/images/kanji/na.png",
    others: [
      { kanji: "有名", hiragana: "ゆうめい", meaning: "နာမည်ကြီးသော" },
      { kanji: "名字", hiragana: "みょうじ", meaning: "မျိုးရိုးအမည်" },
      { kanji: "名刺", hiragana: "めいし", meaning: "လိပ်စာကတ်" },
      {
        kanji: "名物",
        hiragana: "めいぶつ",
        meaning: "နာမည်ကျော်ဒေသထွက်ပစ္စည်း",
      },
    ],
  },
  {
    id: 71,
    level: "n5",
    kanji: "白",
    kunYomi: "shiro(i)",
    onYomi: "haku",
    hiragana: "しろい",
    meaning: "အဖြူရောင်",
    image: "https://api.example.com/images/kanji/shiro.png",
    others: [
      {
        kanji: "面白い",
        hiragana: "おもしろい",
        meaning: "စိတ်ဝင်စားစရာကောင်းသော",
      },
      { kanji: "白髪", hiragana: "しらが", meaning: "ဆံပင်ဖြူ" },
      { kanji: "白鳥", hiragana: "はくちょう", meaning: "ငန်း" },
      { kanji: "白米", hiragana: "はくまい", meaning: "ဆန်ဖြူ" },
    ],
  },
  {
    id: 72,
    level: "n5",
    kanji: "高",
    kunYomi: "taka(i)",
    onYomi: "kou",
    hiragana: "たかい",
    meaning: "မြင့်သော / ဈေးကြီးသော",
    image: "https://api.example.com/images/kanji/takai.png",
    others: [
      {
        kanji: "高校生",
        hiragana: "こうこうせい",
        meaning: "အထက်တန်းကျောင်းသား",
      },
      { kanji: "高級", hiragana: "こうきゅう", meaning: "အဆင့်မြင့် / ဇိမ်ခံ" },
      { kanji: "最高", hiragana: "さいこう", meaning: "အကောင်းဆုံး" },
      { kanji: "高台", hiragana: "たかだい", meaning: "ကုန်းမြင့်" },
    ],
  },
  {
    id: 73,
    level: "n5",
    kanji: "安",
    kunYomi: "yasu(i)",
    onYomi: "an",
    hiragana: "やすい",
    meaning: "ဈေးပေါသော / အေးချမ်းသော",
    image: "https://api.example.com/images/kanji/yasui.png",
    others: [
      { kanji: "安心", hiragana: "あんしん", meaning: "စိတ်အေးရခြင်း" },
      { kanji: "安全", hiragana: "あんぜん", meaning: "ဘေးကင်းလုံခြုံခြင်း" },
      { kanji: "不安", hiragana: "ふあん", meaning: "စိုးရိမ်ပူပန်ခြင်း" },
      {
        kanji: "安売り",
        hiragana: "やすうり",
        meaning: "ဈေးလျှော့ရောင်းခြင်း",
      },
    ],
  },
  {
    id: 74,
    level: "n5",
    kanji: "新",
    kunYomi: "atara(shii)",
    onYomi: "shin",
    hiragana: "あたらしい",
    meaning: "သစ်လွင်သော",
    image: "https://api.example.com/images/kanji/atarashii.png",
    others: [
      { kanji: "新聞", hiragana: "しんぶん", meaning: "သတင်းစာ" },
      { kanji: "新年", hiragana: "しんねん", meaning: "နှစ်သစ်" },
      { kanji: "新幹線", hiragana: "しんかんせん", meaning: "ကျည်ဆန်ရထား" },
      { kanji: "新人", hiragana: "しんじん", meaning: "လူသစ်" },
    ],
  },
  {
    id: 75,
    level: "n5",
    kanji: "古",
    kunYomi: "furu(i)",
    onYomi: "ko",
    hiragana: "ふるい",
    meaning: "ဟောင်းနွမ်းသော",
    image: "https://api.example.com/images/kanji/furui.png",
    others: [
      { kanji: "中古", hiragana: "ちゅうこ", meaning: "တစ်ပတ်ရစ်" },
      { kanji: "古本", hiragana: "ふるほん", meaning: "စာအုပ်ဟောင်း" },
      { kanji: "古都", hiragana: "こと", meaning: "မြို့ဟောင်း" },
      { kanji: "古里", hiragana: "ふるさと", meaning: "ဇာတိမြေ" },
    ],
  },
  {
    id: 76,
    level: "n5",
    kanji: "目",
    kunYomi: "me",
    onYomi: "moku",
    hiragana: "め",
    meaning: "မျက်စိ",
    image: "https://api.example.com/images/kanji/me.png",
    others: [
      { kanji: "目上", hiragana: "めうえ", meaning: "အထက်လူကြီး" },
      { kanji: "目下", hiragana: "めした", meaning: "လက်အောက်ငယ်သား" },
      { kanji: "目次", hiragana: "もくじ", meaning: "မာတိကာ" },
      { kanji: "目的", hiragana: "もくてき", meaning: "ရည်ရွယ်ချက်" },
    ],
  },
  {
    id: 77,
    level: "n5",
    kanji: "耳",
    kunYomi: "mimi",
    onYomi: "ji",
    hiragana: "みみ",
    meaning: "နား",
    image: "https://api.example.com/images/kanji/mimi.png",
    others: [
      {
        kanji: "耳鼻科",
        hiragana: "じびか",
        meaning: "နား၊ နှာခေါင်း၊ လည်ချောင်းဌာန",
      },
      {
        kanji: "初耳",
        hiragana: "はつみみ",
        meaning: "ပထမဆုံးအကြိမ်ကြားဖူးခြင်း",
      },
      { kanji: "耳鳴り", hiragana: "みみなり", meaning: "နားအူခြင်း" },
      { kanji: "耳飾り", hiragana: "みみかざり", meaning: "နားကပ်" },
    ],
  },
  {
    id: 78,
    level: "n5",
    kanji: "口",
    kunYomi: "kuchi",
    onYomi: "kou",
    hiragana: "くち",
    meaning: "ပါးစပ် / အပေါက်",
    image: "https://api.example.com/images/kanji/kuchi.png",
    others: [
      { kanji: "入口", hiragana: "いりぐち", meaning: "အဝင်ပေါက်" },
      { kanji: "出口", hiragana: "でぐち", meaning: "အထွက်ပေါက်" },
      { kanji: "窓口", hiragana: "まどぐち", meaning: "ဝန်ဆောင်မှုကောင်တာ" },
      { kanji: "人口", hiragana: "じんこう", meaning: "လူဦးရေ" },
    ],
  },
  {
    id: 79,
    level: "n5",
    kanji: "手",
    kunYomi: "te",
    onYomi: "shu",
    hiragana: "て",
    meaning: "လက်",
    image: "https://api.example.com/images/kanji/te.png",
    others: [
      { kanji: "お手洗い", hiragana: "おてあらい", meaning: "အိမ်သာ" },
      { kanji: "切手", hiragana: "きって", meaning: "တံဆိပ်ခေါင်း" },
      { kanji: "歌手", hiragana: "かしゅ", meaning: "အဆိုတော်" },
      { kanji: "下手", hiragana: "へた", meaning: "မကျွမ်းကျင်သော" },
    ],
  },
  {
    id: 80,
    level: "n5",
    kanji: "足",
    kunYomi: "ashi / ta(ru)",
    onYomi: "soku",
    hiragana: "あし",
    meaning: "ခြေထောက် / လုံလောက်သည်",
    image: "https://api.example.com/images/kanji/ashi.png",
    others: [
      { kanji: "遠足", hiragana: "えんそく", meaning: "အပျော်ခရီးထွက်ခြင်း" },
      { kanji: "足りる", hiragana: "たりる", meaning: "လုံလောက်သည်" },
      { kanji: "不足", hiragana: "ふそく", meaning: "မလုံလောက်ခြင်း" },
      {
        kanji: "一足",
        hiragana: "いっそく",
        meaning: "တစ်စုံ (ဖိနပ်/ခြေအိတ်)",
      },
    ],
  },
  {
    id: 81,
    level: "n5",
    kanji: "力",
    kunYomi: "chikara",
    onYomi: "ryoku / riki",
    hiragana: "ちから",
    meaning: "အင်အား / စွမ်းအား",
    image: "https://api.example.com/images/kanji/chikara.png",
    others: [
      {
        kanji: "協力",
        hiragana: "きょうりょく",
        meaning: "ပူးပေါင်းဆောင်ရွက်ခြင်း",
      },
      { kanji: "実力", hiragana: "じつりょく", meaning: "တကယ့်စွမ်းရည်" },
      { kanji: "電力", hiragana: "でんりょく", meaning: "လျှပ်စစ်စွမ်းအား" },
      { kanji: "火力", hiragana: "かりょく", meaning: "မီးအင်အား" },
    ],
  },
  {
    id: 82,
    level: "n5",
    kanji: "出",
    kunYomi: "de(ru) / da(su)",
    onYomi: "shutsu",
    hiragana: "でる",
    meaning: "ထွက်သည် / ထုတ်သည်",
    image: "https://api.example.com/images/kanji/deru.png",
    others: [
      { kanji: "出口", hiragana: "でぐち", meaning: "အထွက်ပေါက်" },
      { kanji: "外出", hiragana: "がいしゅつ", meaning: "အပြင်ထွက်ခြင်း" },
      { kanji: "思い出", hiragana: "おもいで", meaning: "အမှတ်တရ" },
      { kanji: "出す", hiragana: "だす", meaning: "ထုတ်သည် / ပို့သည်" },
    ],
  },
  {
    id: 83,
    level: "n5",
    kanji: "入",
    kunYomi: "hai(ru) / i(reru)",
    onYomi: "nyuu",
    hiragana: "はいる",
    meaning: "ဝင်သည် / ထည့်သည်",
    image: "https://api.example.com/images/kanji/hairu.png",
    others: [
      { kanji: "入口", hiragana: "いりぐち", meaning: "အဝင်ပေါက်" },
      { kanji: "入院", hiragana: "にゅういん", meaning: "ဆေးရုံတက်ခြင်း" },
      { kanji: "入学", hiragana: "にゅうがく", meaning: "ကျောင်းဝင်ခြင်း" },
      { kanji: "入れる", hiragana: "いれる", meaning: "ထည့်သည်" },
    ],
  },
  {
    id: 84,
    level: "n5",
    kanji: "立",
    kunYomi: "ta(tsu)",
    onYomi: "ritsu",
    hiragana: "たつ",
    meaning: "မတ်တပ်ရပ်သည်",
    image: "https://api.example.com/images/kanji/tatsu.png",
    others: [
      { kanji: "国立", hiragana: "こくりつ", meaning: "နိုင်ငံတော်ပိုင်" },
      { kanji: "私立", hiragana: "しりつ", meaning: "ပုဂ္ဂလိကပိုင်" },
      { kanji: "目立つ", hiragana: "めだつ", meaning: "ထင်ရှားပေါ်လွင်သည်" },
      { kanji: "立場", hiragana: "たちば", meaning: "ရပ်တည်ချက် / အခြေအနေ" },
    ],
  },
  {
    id: 85,
    level: "n5",
    kanji: "休",
    kunYomi: "yasu(mu)",
    onYomi: "kyuu",
    hiragana: "やすむ",
    meaning: "နားသည် / ကျောင်းပိတ်သည်",
    image: "https://api.example.com/images/kanji/yasumu.png",
    others: [
      { kanji: "休み", hiragana: "やすみ", meaning: "အားလပ်ရက်" },
      { kanji: "休日", hiragana: "きゅうじつ", meaning: "နားရက်" },
      {
        kanji: "夏休み",
        hiragana: "なつやすみ",
        meaning: "နွေရာသီကျောင်းပိတ်ရက်",
      },
      { kanji: "連休", hiragana: "れんきゅう", meaning: "ဆက်တိုက်အားလပ်ရက်" },
    ],
  },
  {
    id: 86,
    level: "n5",
    kanji: "走",
    kunYomi: "hashi(ru)",
    onYomi: "sou",
    hiragana: "はしる",
    meaning: "ပြေးသည်",
    image: "https://api.example.com/images/kanji/hashiru.png",
    others: [
      { kanji: "走る", hiragana: "はしる", meaning: "ပြေးသည်" },
      { kanji: "競走", hiragana: "きょうそう", meaning: "အပြေးပြိုင်ခြင်း" },
      {
        kanji: "脱走",
        hiragana: "だっそう",
        meaning: "ထွက်ပြေးလွတ်မြောက်ခြင်း",
      },
      { kanji: "走行", hiragana: "そうこう", meaning: "မောင်းနှင်ခြင်း" },
    ],
  },
  {
    id: 87,
    level: "n5",
    kanji: "空",
    kunYomi: "sora / a(ku) / kara",
    onYomi: "kuu",
    hiragana: "そら",
    meaning: "ကောင်းကင် / အားသော / ဗလာ",
    image: "https://api.example.com/images/kanji/sora.png",
    others: [
      { kanji: "空気", hiragana: "くうき", meaning: "လေထု" },
      { kanji: "空港", hiragana: "くうこう", meaning: "လေဆိပ်" },
      { kanji: "空手", hiragana: "からて", meaning: "ကရာတေး" },
      { kanji: "空席", hiragana: "くうせき", meaning: "လွတ်နေသောနေရာ" },
    ],
  },
  {
    id: 88,
    level: "n5",
    kanji: "海",
    kunYomi: "umi",
    onYomi: "kai",
    hiragana: "うみ",
    meaning: "ပင်လယ်",
    image: "https://api.example.com/images/kanji/umi.png",
    others: [
      { kanji: "海外", hiragana: "かいがい", meaning: "နိုင်ငံရပ်ခြား" },
      {
        kanji: "海水浴",
        hiragana: "かいすいよく",
        meaning: "ပင်လယ်ရေချိုးခြင်း",
      },
      { kanji: "北海道", hiragana: "ほっかいどう", meaning: "ဟော့ကိုင်းဒိုး" },
      { kanji: "地中海", hiragana: "ちちゅうかい", meaning: "မြေထဲပင်လယ်" },
    ],
  },
  {
    id: 89,
    level: "n5",
    kanji: "花",
    kunYomi: "hana",
    onYomi: "ka",
    hiragana: "はな",
    meaning: "ပန်း",
    image: "https://api.example.com/images/kanji/hana.png",
    others: [
      { kanji: "花見", hiragana: "はなみ", meaning: "ပန်းကြည့်ပွဲ" },
      { kanji: "花火", hiragana: "はなび", meaning: "မီးရှူးမီးပန်း" },
      { kanji: "花瓶", hiragana: "かびん", meaning: "ပန်းအိုး" },
      { kanji: "生け花", hiragana: "いけばな", meaning: "ဂျပန်ပန်းအလှပြင်ပညာ" },
    ],
  },
  {
    id: 90,
    level: "n5",
    kanji: "赤",
    kunYomi: "aka(i)",
    onYomi: "seki",
    hiragana: "あかい",
    meaning: "အနီရောင်",
    image: "https://api.example.com/images/kanji/aka.png",
    others: [
      { kanji: "赤ちゃん", hiragana: "あかちゃん", meaning: "ကလေးငယ်" },
      { kanji: "赤道", hiragana: "せကိどう", meaning: "အီကွေတာ" },
      { kanji: "赤十字", hiragana: "せきじゅうじ", meaning: "ကြက်ခြေနီ" },
      { kanji: "赤字", hiragana: "あかじ", meaning: "အရှုံးပြခြင်း" },
    ],
  },
  {
    id: 91,
    level: "n5",
    kanji: "青",
    kunYomi: "ao(i)",
    onYomi: "sei",
    hiragana: "あおい",
    meaning: "အပြာရောင်",
    image: "https://api.example.com/images/kanji/ao.png",
    others: [
      { kanji: "青空", hiragana: "あおぞら", meaning: "ပြာလွင်သောကောင်းကင်" },
      { kanji: "青年", hiragana: "せいねん", meaning: "လူငယ်" },
      { kanji: "青森県", hiragana: "あおもりけん", meaning: "အအိုမိုရိခရိုင်" },
      {
        kanji: "信号",
        hiragana: "しんごう",
        meaning: "မီးပွိုင့် (အပြာရောင်မီး)",
      },
    ],
  },
  {
    id: 92,
    level: "n5",
    kanji: "時",
    kunYomi: "toki",
    onYomi: "ji",
    hiragana: "とき",
    meaning: "အချိန် / နာရီ",
    image: "https://api.example.com/images/kanji/ji.png",
    others: [
      {
        kanji: "時間",
        hiragana: "じかん",
        meaning: "အချိန် / နာရီ (ကြာချိန်)",
      },
      { kanji: "時計", hiragana: "とけい", meaning: "နာရီ (Watch)" },
      { kanji: "時々", hiragana: "ときどき", meaning: "တစ်ခါတစ်ရံ" },
      { kanji: "同時に", hiragana: "どうじに", meaning: "တစ်ပြိုင်နက်တည်း" },
    ],
  },
  {
    id: 93,
    level: "n5",
    kanji: "分",
    kunYomi: "wa(karu) / wa(keru)",
    onYomi: "fun / bun",
    hiragana: "ふん",
    meaning: "မိနစ် / နားလည်သည် / ပိုင်းခြားသည်",
    image: "https://api.example.com/images/kanji/fun.png",
    others: [
      { kanji: "五分", hiragana: "ごふん", meaning: "ငါးမိနစ်" },
      { kanji: "分かる", hiragana: "わかる", meaning: "နားလည်သည်" },
      { kanji: "半分", hiragana: "はんぶん", meaning: "တစ်ဝက်" },
      { kanji: "自分", hiragana: "じぶん", meaning: "မိမိကိုယ်တိုင်" },
    ],
  },
  {
    id: 94,
    level: "n5",
    kanji: "半",
    kunYomi: "なか(ば)",
    onYomi: "han",
    hiragana: "はん",
    meaning: "တစ်ဝက်",
    image: "https://api.example.com/images/kanji/han.png",
    others: [
      { kanji: "三時半", hiragana: "さんじはん", meaning: "သုံးနာရီခွဲ" },
      { kanji: "半年", hiragana: "はんとし", meaning: "နှစ်ဝက်" },
      { kanji: "半島", hiragana: "はんとう", meaning: "ကျွန်းဆွယ်" },
      { kanji: "半分", hiragana: "はんぶん", meaning: "တစ်ဝက်" },
    ],
  },
  {
    id: 95,
    level: "n5",
    kanji: "午",
    kunYomi: "N/A",
    onYomi: "go",
    hiragana: "ご",
    meaning: "မွန်းတည့်",
    image: "https://api.example.com/images/kanji/go_time.png",
    others: [
      { kanji: "午前", hiragana: "ごぜん", meaning: "နံနက်ပိုင်း (AM)" },
      { kanji: "午後", hiragana: "ごご", meaning: "မွန်းလွဲပိုင်း (PM)" },
      { kanji: "正午", hiragana: "しょうご", meaning: "မွန်းတည့် ၁၂ နာရီ" },
      {
        kanji: "午前中",
        hiragana: "ごぜんちゅう",
        meaning: "နံနက်ပိုင်းတစ်လျှောက်",
      },
    ],
  },
  {
    id: 96,
    level: "n5",
    kanji: "万",
    kunYomi: "N/A",
    onYomi: "man / ban",
    hiragana: "まん",
    meaning: "တစ်သောင်း",
    image: "https://api.example.com/images/kanji/man.png",
    others: [
      { kanji: "一万円", hiragana: "いちまんえん", meaning: "တစ်သောင်းယန်း" },
      { kanji: "万一", hiragana: "まんいち", meaning: "မတော်တဆ / အကယ်၍" },
      {
        kanji: "万歳",
        hiragana: "ばんざい",
        meaning: "ဘန်ဇိုင်း (အောင်ပွဲခံအော်ဟစ်သံ)",
      },
      { kanji: "万年筆", hiragana: "まんねんひつ", meaning: "ဖောင်တိန်" },
    ],
  },
  {
    id: 97,
    level: "n5",
    kanji: "語",
    kunYomi: "kata(ru)",
    onYomi: "go",
    hiragana: "ご",
    meaning: "ဘာသာစကား / ပြောပြသည်",
    image: "https://api.example.com/images/kanji/go_lang.png",
    others: [
      { kanji: "日本語", hiragana: "にほんご", meaning: "ဂျပန်ဘာသာစကား" },
      { kanji: "英語", hiragana: "えいご", meaning: "အင်္ဂလိပ်ဘာသာစကား" },
      { kanji: "単語", hiragana: "たんご", meaning: "ဝေါဟာရ" },
      { kanji: "物語", hiragana: "ものかたり", meaning: "ပုံပြင် / ဇာတ်လမ်း" },
    ],
  },
  {
    id: 98,
    level: "n5",
    kanji: "物",
    kunYomi: "mono",
    onYomi: "butsu / motsu",
    hiragana: "もの",
    meaning: "ပစ္စည်း / အရာဝတ္ထု",
    image: "https://api.example.com/images/kanji/mono.png",
    others: [
      { kanji: "食べ物", hiragana: "たべもの", meaning: "အစားအစာ" },
      { kanji: "買い物", hiragana: "かいもの", meaning: "ဈေးဝယ်ခြင်း" },
      { kanji: "動物", hiragana: "どうぶつ", meaning: "တိရစ္ဆာန်" },
      { kanji: "荷物", hiragana: "にもつ", meaning: "အထုပ်အပိုး" },
    ],
  },
  {
    id: 99,
    level: "n5",
    kanji: "社",
    kunYomi: "yashiro",
    onYomi: "sha",
    hiragana: "しゃ",
    meaning: "ကုမ္ပဏီ / နတ်စင်",
    image: "https://api.example.com/images/kanji/sha.png",
    others: [
      { kanji: "会社", hiragana: "かいしゃ", meaning: "ကုမ္ပဏီ" },
      { kanji: "社会", hiragana: "しゃかい", meaning: "လူ့အဖွဲ့အစည်း" },
      {
        kanji: "神社",
        hiragana: "じんじゃ",
        meaning: "ဂျပန်ဘုရားကျောင်း / နတ်စင်",
      },
      { kanji: "社長", hiragana: "しゃちょう", meaning: "ကုမ္ပဏီဥက္ကဌ" },
    ],
  },
  {
    id: 100,
    level: "n5",
    kanji: "会",
    kunYomi: "a(u)",
    onYomi: "kai / e",
    hiragana: "あう",
    meaning: "တွေ့ဆုံသည် / အဖွဲ့အစည်း",
    image: "https://api.example.com/images/kanji/kai.png",
    others: [
      { kanji: "会話", hiragana: "かいわ", meaning: "စကားပြောဆိုခြင်း" },
      { kanji: "会議", hiragana: "かいぎ", meaning: "အစည်းအဝေး" },
      { kanji: "会場", hiragana: "かいじょう", meaning: "ကျင်းပရာနေရာ" },
      {
        kanji: "大会",
        hiragana: "たいかい",
        meaning: "ပြိုင်ပွဲကြီး / ညီလာခံ",
      },
    ],
  },

  {
    id: 101,
    level: "n5",
    kanji: "家",
    kunYomi: "ie / ya",
    onYomi: "ka / ke",
    hiragana: "いえ",
    meaning: "အိမ်",
    image: "https://api.example.com/images/kanji/ie.png",
    others: [
      { kanji: "家族", hiragana: "かぞく", meaning: "မိသားစု" },
      { kanji: "家庭", hiragana: "かてい", meaning: "အိမ်ထောင်စု" },
      { kanji: "家主", hiragana: "やぬし", meaning: "အိမ်ရှင်" },
      { kanji: "家事", hiragana: "かじ", meaning: "အိမ်အလုပ်" },
    ],
  },
  {
    id: 102,
    level: "n5",
    kanji: "店",
    kunYomi: "mise",
    onYomi: "ten",
    hiragana: "みせ",
    meaning: "ဆိုင်",
    image: "https://api.example.com/images/kanji/mise.png",
    others: [
      { kanji: "喫茶店", hiragana: "きっさてん", meaning: "ကော်ဖီဆိုင်" },
      { kanji: "書店", hiragana: "しょてん", meaning: "စာအုပ်ဆိုင်" },
      { kanji: "店員", hiragana: "てんいん", meaning: "ဆိုင်ဝန်ထမ်း" },
      { kanji: "売店", hiragana: "ばいてん", meaning: "အရောင်းဆိုင်" },
    ],
  },
  {
    id: 103,
    level: "n5",
    kanji: "駅",
    kunYomi: "N/A",
    onYomi: "eki",
    hiragana: "えき",
    meaning: "ဘူတာရုံ",
    image: "https://api.example.com/images/kanji/eki.png",
    others: [
      { kanji: "駅長", hiragana: "えきちょう", meaning: "ဘူတာရုံပိုင်" },
      { kanji: "駅員", hiragana: "えきいん", meaning: "ဘူတာရုံဝန်ထမ်း" },
      { kanji: "駅前", hiragana: "えきまえ", meaning: "ဘူတာရှေ့" },
      { kanji: "東京駅", hiragana: "とうきょうえき", meaning: "တိုကျိုဘူတာ" },
    ],
  },
  {
    id: 104,
    level: "n5",
    kanji: "銀",
    kunYomi: "shirogane",
    onYomi: "gin",
    hiragana: "ぎん",
    meaning: "ငွေ (Silver)",
    image: "https://api.example.com/images/kanji/gin.png",
    others: [
      { kanji: "銀行", hiragana: "ぎんこう", meaning: "ဘဏ်" },
      { kanji: "銀メダル", hiragana: "ぎんめだる", meaning: "ငွေတံဆိပ်" },
      { kanji: "銀座", hiragana: "ぎんざ", meaning: "ဂင်းဇာ (ရပ်ကွက်အမည်)" },
      { kanji: "銀色", hiragana: "ぎんいろ", meaning: "ငွေရောင်" },
    ],
  },
  {
    id: 105,
    level: "n5",
    kanji: "道",
    kunYomi: "michi",
    onYomi: "dou",
    hiragana: "みち",
    meaning: "လမ်း / နည်းလမ်း",
    image: "https://api.example.com/images/kanji/michi.png",
    others: [
      { kanji: "水道", hiragana: "すいどう", meaning: "ရေပိုက်ခေါင်း" },
      { kanji: "書道", hiragana: "しょどう", meaning: "ဂျပန်လက်ရေးလှပညာ" },
      { kanji: "柔道", hiragana: "じゅうどう", meaning: "ဂျူဒို" },
      { kanji: "道路", hiragana: "どうろ", meaning: "လမ်းမ" },
    ],
  },
  {
    id: 106,
    level: "n5",
    kanji: "電",
    kunYomi: "N/A",
    onYomi: "den",
    hiragana: "でん",
    meaning: "လျှပ်စစ်",
    image: "https://api.example.com/images/kanji/den.png",
    others: [
      { kanji: "電車", hiragana: "でんしゃ", meaning: "လျှပ်စစ်ရထား" },
      { kanji: "電話", hiragana: "でんわ", meaning: "ဖုန်း" },
      { kanji: "電気", hiragana: "でんき", meaning: "လျှပ်စစ်မီး" },
      { kanji: "電子メール", hiragana: "でんしめーる", meaning: "အီးမေးလ်" },
    ],
  },
  {
    id: 107,
    level: "n5",
    kanji: "京",
    kunYomi: "miyako",
    onYomi: "kyou / kei",
    hiragana: "きょう",
    meaning: "မြို့တော်",
    image: "https://api.example.com/images/kanji/kyou.png",
    others: [
      { kanji: "東京", hiragana: "とうきょう", meaning: "တိုကျို" },
      { kanji: "京都", hiragana: "きょうと", meaning: "ကျိုတို" },
      {
        kanji: "京浜",
        hiragana: "けいひん",
        meaning: "တိုကျိုနှင့်ယိုကိုဟားမားဒေသ",
      },
      {
        kanji: "上京",
        hiragana: "じょうきょう",
        meaning: "မြို့တော်သို့တက်လာခြင်း",
      },
    ],
  },
  {
    id: 108,
    level: "n5",
    kanji: "国",
    kunYomi: "kuni",
    onYomi: "koku",
    hiragana: "くに",
    meaning: "နိုင်ငံ",
    image: "https://api.example.com/images/kanji/koku.png",
    others: [
      { kanji: "外国", hiragana: "がいこく", meaning: "နိုင်ငံခြား" },
      { kanji: "中国", hiragana: "ちゅうごく", meaning: "တရုတ်နိုင်ငံ" },
      { kanji: "国籍", hiragana: "こくせき", meaning: "နိုင်ငံသားဖြစ်မှု" },
      { kanji: "国会", hiragana: "こっかい", meaning: "လွှတ်တော်" },
    ],
  },
  {
    id: 109,
    level: "n5",
    kanji: "外",
    kunYomi: "soto / hoka",
    onYomi: "gai / ge",
    hiragana: "そと",
    meaning: "အပြင်",
    image: "https://api.example.com/images/kanji/soto.png",
    others: [
      { kanji: "外国人", hiragana: "がいこくじん", meaning: "နိုင်ငံခြားသား" },
      { kanji: "海外", hiragana: "かいがい", meaning: "ပင်လယ်ရပ်ခြား" },
      { kanji: "外出", hiragana: "がいしゅつ", meaning: "အပြင်ထွက်ခြင်း" },
      { kanji: "意外", hiragana: "いがい", meaning: "မမျှော်လင့်ထားသော" },
    ],
  },
  {
    id: 110,
    level: "n5",
    kanji: "多",
    kunYomi: "oo(i)",
    onYomi: "ta",
    hiragana: "おおい",
    meaning: "များသော",
    image: "https://api.example.com/images/kanji/ooi.png",
    others: [
      { kanji: "多分", hiragana: "たぶん", meaning: "ဖြစ်နိုင်ချေရှိသော" },
      { kanji: "多数", hiragana: "たすう", meaning: "အများစု" },
      { kanji: "多少", hiragana: "たしょう", meaning: "အနည်းငယ်" },
      { kanji: "多忙", hiragana: "たぼう", meaning: "အလွန်အလုပ်ရှုပ်သော" },
    ],
  },
  {
    id: 111,
    level: "n5",
    kanji: "小",
    kunYomi: "chii(sai) / ko / o",
    onYomi: "shou",
    hiragana: "ちいさい",
    meaning: "သေးငယ်သော",
    image: "https://api.example.com/images/kanji/chiisai.png",
    others: [
      {
        kanji: "小学校",
        hiragana: "しょうがっこう",
        meaning: "မူလတန်းကျောင်း",
      },
      { kanji: "小説", hiragana: "しょうせつ", meaning: "ဝတ္ထု" },
      { kanji: "小包", hiragana: "こづつみ", meaning: "ချောထုပ်" },
      { kanji: "小麦", hiragana: "こむぎ", meaning: "ဂျုံ" },
    ],
  },
  {
    id: 112,
    level: "n5",
    kanji: "少",
    kunYomi: "suku(nai) / suko(shi)",
    onYomi: "shou",
    hiragana: "すくない",
    meaning: "နည်းသော",
    image: "https://api.example.com/images/kanji/sukunai.png",
    others: [
      { kanji: "少し", hiragana: "すこし", meaning: "နည်းနည်း" },
      { kanji: "少年", hiragana: "しょうねん", meaning: "ယောက်ျားလေး" },
      { kanji: "少女", hiragana: "しょうじょ", meaning: "မိန်းကလေး" },
      {
        kanji: "少々",
        hiragana: "しょうしょう",
        meaning: "ခဏလောက် / နည်းနည်းလောက်",
      },
    ],
  },
  {
    id: 113,
    level: "n5",
    kanji: "長",
    kunYomi: "naga(i)",
    onYomi: "chou",
    hiragana: "ながい",
    meaning: "ရှည်လျားသော / ခေါင်းဆောင်",
    image: "https://api.example.com/images/kanji/nagai.png",
    others: [
      { kanji: "社長", hiragana: "しゃちょう", meaning: "ဥက္ကဌ" },
      { kanji: "身長", hiragana: "しんちょう", meaning: "အရပ်အမောင်း" },
      { kanji: "長男", hiragana: "ちょうなん", meaning: "သားကြီး" },
      { kanji: "長所", hiragana: "ちょうしょ", meaning: "အားသာချက်" },
    ],
  },
  {
    id: 114,
    level: "n5",
    kanji: "高",
    kunYomi: "taka(i)",
    onYomi: "kou",
    hiragana: "たかい",
    meaning: "မြင့်သော / ဈေးကြီးသော",
    image: "https://api.example.com/images/kanji/takai.png",
    others: [
      { kanji: "高校", hiragana: "こうこう", meaning: "အထက်တန်းကျောင်း" },
      { kanji: "高級", hiragana: "こうきゅう", meaning: "အဆင့်မြင့်" },
      { kanji: "最高", hiragana: "さいこう", meaning: "အကောင်းဆုံး" },
      { kanji: "高速", hiragana: "こうそく", meaning: "အရှိန်ပြင်းသော" },
    ],
  },
  {
    id: 115,
    level: "n5",
    kanji: "安",
    kunYomi: "yasu(i)",
    onYomi: "an",
    hiragana: "やすい",
    meaning: "ဈေးပေါသော / အေးချမ်းသော",
    image: "https://api.example.com/images/kanji/yasui.png",
    others: [
      { kanji: "安心", hiragana: "あんしん", meaning: "စိတ်အေးရခြင်း" },
      { kanji: "安全", hiragana: "あんぜん", meaning: "ဘေးကင်းလုံခြုံခြင်း" },
      { kanji: "不安", hiragana: "ふあん", meaning: "စိုးရိမ်ပူပန်ခြင်း" },
      {
        kanji: "安売り",
        hiragana: "やすうり",
        meaning: "ဈေးလျှော့ရောင်းခြင်း",
      },
    ],
  },
  {
    id: 116,
    level: "n5",
    kanji: "新",
    kunYomi: "atara(shii) / ara(ta)",
    onYomi: "shin",
    hiragana: "あたらしい",
    meaning: "သစ်လွင်သော",
    image: "https://api.example.com/images/kanji/atarashii.png",
    others: [
      { kanji: "新聞", hiragana: "しんぶん", meaning: "သတင်းစာ" },
      { kanji: "新年", hiragana: "しんねん", meaning: "နှစ်သစ်" },
      { kanji: "新幹線", hiragana: "しんかんせん", meaning: "ကျည်ဆန်ရထား" },
      { kanji: "新鮮", hiragana: "しんせん", meaning: "လတ်ဆတ်သော" },
    ],
  },
  {
    id: 117,
    level: "n5",
    kanji: "古",
    kunYomi: "furu(i)",
    onYomi: "ko",
    hiragana: "ふるい",
    meaning: "ဟောင်းနွမ်းသော",
    image: "https://api.example.com/images/kanji/furui.png",
    others: [
      { kanji: "中古", hiragana: "ちゅうこ", meaning: "တစ်ပတ်ရစ်" },
      { kanji: "古本", hiragana: "ふるほん", meaning: "စာအုပ်ဟောင်း" },
      { kanji: "古代", hiragana: "こだい", meaning: "ရှေးခေတ်" },
      { kanji: "古都", hiragana: "こと", meaning: "မြို့ဟောင်း" },
    ],
  },
  {
    id: 118,
    level: "n5",
    kanji: "早",
    kunYomi: "haya(i)",
    onYomi: "sou",
    hiragana: "はやい",
    meaning: "စောသော",
    image: "https://api.example.com/images/kanji/hayai.png",
    others: [
      { kanji: "早速", hiragana: "さっそく", meaning: "ချက်ချင်း" },
      { kanji: "早朝", hiragana: "そうちょう", meaning: "မနက်စောစော" },
      { kanji: "早退", hiragana: "そうたい", meaning: "စောစောပြန်ခြင်း" },
      { kanji: "早寝", hiragana: "はやね", meaning: "စောစောအိပ်ခြင်း" },
    ],
  },
  {
    id: 119,
    level: "n5",
    kanji: "北",
    kunYomi: "kita",
    onYomi: "hoku",
    hiragana: "きた",
    meaning: "မြောက်ဘက်",
    image: "https://api.example.com/images/kanji/kita.png",
    others: [
      { kanji: "北海道", hiragana: "ほっかいどう", meaning: "ဟော့ကိုင်းဒိုး" },
      { kanji: "南北", hiragana: "なんぼく", meaning: "တောင်နှင့်မြောက်" },
      { kanji: "北極", hiragana: "ほっきょく", meaning: "မြောက်ဝင်ရိုးစွန်း" },
      { kanji: "北欧", hiragana: "ほくおう", meaning: "ဥရောပမြောက်ပိုင်း" },
    ],
  },
  {
    id: 120,
    level: "n5",
    kanji: "南",
    kunYomi: "minami",
    onYomi: "nan",
    hiragana: "みなみ",
    meaning: "တောင်ဘက်",
    image: "https://api.example.com/images/kanji/minami.png",
    others: [
      { kanji: "東南", hiragana: "とうなん", meaning: "အရှေ့တောင်" },
      { kanji: "南極", hiragana: "なんきょく", meaning: "တောင်ဝင်ရိုးစွန်း" },
      { kanji: "南米", hiragana: "なんべい", meaning: "တောင်အမေရိက" },
      { kanji: "南側", hiragana: "みなみがわ", meaning: "တောင်ဘက်ခြမ်း" },
    ],
  },
  {
    id: 121,
    level: "n5",
    kanji: "西",
    kunYomi: "nishi",
    onYomi: "sei / sai",
    hiragana: "にし",
    meaning: "အနောက်ဘက်",
    image: "https://api.example.com/images/kanji/nishi.png",
    others: [
      { kanji: "関西", hiragana: "かんさい", meaning: "ခန်းဆိုင်းဒေသ" },
      { kanji: "西洋", hiragana: "せいよう", meaning: "အနောက်တိုင်း" },
      { kanji: "南西", hiragana: "なんせい", meaning: "တောင်အနောက်" },
      { kanji: "西暦", hiragana: "せいれき", meaning: "အေဒီခုနှစ်" },
    ],
  },
  {
    id: 122,
    level: "n5",
    kanji: "東",
    kunYomi: "higashi",
    onYomi: "tou",
    hiragana: "ひがし",
    meaning: "အရှေ့ဘက်",
    image: "https://api.example.com/images/kanji/higashi.png",
    others: [
      { kanji: "東京", hiragana: "とうきょう", meaning: "တိုကျို" },
      { kanji: "関東", hiragana: "かんとう", meaning: "ခန်းတိုးဒေသ" },
      { kanji: "東洋", hiragana: "とうよう", meaning: "အရှေ့တိုင်း" },
      { kanji: "中東", hiragana: "ちゅうとう", meaning: "အရှေ့အလယ်ပိုင်း" },
    ],
  },
  {
    id: 123,
    level: "n5",
    kanji: "週",
    kunYomi: "N/A",
    onYomi: "shuu",
    hiragana: "しゅう",
    meaning: "အပတ်",
    image: "https://api.example.com/images/kanji/shuu.png",
    others: [
      { kanji: "一週間", hiragana: "いっしゅうかん", meaning: "တစ်ပတ်တာ" },
      { kanji: "来週", hiragana: "らいしゅう", meaning: "နောက်အပတ်" },
      { kanji: "先週", hiragana: "せんしゅう", meaning: "ပြီးခဲ့သည့်အပတ်" },
      { kanji: "毎週", hiragana: "まいしゅう", meaning: "အပတ်တိုင်း" },
    ],
  },
  {
    id: 124,
    level: "n5",
    kanji: "天",
    kunYomi: "ama",
    onYomi: "ten",
    hiragana: "あま",
    meaning: "ကောင်းကင်",
    image: "https://api.example.com/images/kanji/ten.png",
    others: [
      { kanji: "天気", hiragana: "てんき", meaning: "ရာသီဥတု" },
      {
        kanji: "天国",
        hiragana: "てんごく",
        meaning: "နိဗ္ဗာန် / ကောင်းကင်ဘုံ",
      },
      { kanji: "天才", hiragana: "てんさい", meaning: "ပါရမီရှင်" },
      { kanji: "天然", hiragana: "てんねん", meaning: "သဘာဝအတိုင်း" },
    ],
  },
  {
    id: 125,
    level: "n5",
    kanji: "白",
    kunYomi: "shiro(i)",
    onYomi: "haku",
    hiragana: "しろい",
    meaning: "အဖြူရောင်",
    image: "https://api.example.com/images/kanji/shiro.png",
    others: [
      {
        kanji: "面白い",
        hiragana: "おもしろい",
        meaning: "စိတ်ဝင်စားစရာကောင်းသော",
      },
      { kanji: "白鳥", hiragana: "はくちょう", meaning: "ငန်း" },
      { kanji: "白米", hiragana: "はくまい", meaning: "ဆန်ဖြူ" },
      { kanji: "白紙", hiragana: "はくし", meaning: "စာရွက်အလွတ်" },
    ],
  },
];
